### ISSUE TITLE
Task02 - Adicionar Cupom de Desconto

### ISSUE THREAD

**Issue by falcettijr** [falcettijr/Shopping-Cart-JavaScript#5]

**Comment by leoap** [comment]
#Task02
Programar um campo de texto que receba um Código de Cupom do usuário.
O Código de Cupom inserido deve ser validado junto à uma lista com Códigos de Cupom ativos, a ser criada por você mesmo no próprio código.
Caso seja válido, o Código de Cupom inserido deve decrementar o Valor Total do Carrinho em um percentual à sua escolha (se conseguir, atribua um Valor Percentual individual à cada Código de Cupom ativo.
Caso seja inválido, uma mensagem de alerta deve ser exibida ao Usuário.

**Comment by falcettijr** [comment]
### Funcionalidade implementada 
 para testar use os cupons:

**CUPOM1** - 10% de Desconto
**CUPOM2** - 20% de Desconto

Também fiz o [deploy](https://falcettijr.github.io/Shopping-Cart-JavaScript/) do projeto.
